/**
 * 素材图库 — 小红书/社交媒体热门表情 & 拼豆创意素材
 * 使用 Twemoji (Twitter开源表情, CC-BY 4.0)
 * 精选适合做拼豆的高辨识度图案，颜色鲜明、轮廓清晰
 * CDN: https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/
 */
const _T = code => `https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/${code}.png`;

const GALLERY_DATA = [
  {
    id: 'xhs-hot',
    name: '🔥 小红书热门',
    items: [
      { name: '🥺 楚楚可怜',   url: _T('1f97a') },
      { name: '🫠 我融化了',   url: _T('1fae0') },
      { name: '🤭 偷笑',       url: _T('1f92d') },
      { name: '😭 哭死我了',   url: _T('1f62d') },
      { name: '🥹 感动哭',     url: _T('1f979') },
      { name: '😍 心动了',     url: _T('1f60d') },
      { name: '🤩 追星脸',     url: _T('1f929') },
      { name: '🥰 被宠爱',     url: _T('1f970') },
      { name: '😏 懂的都懂',   url: _T('1f60f') },
      { name: '🤡 小丑竟是我', url: _T('1f921') },
      { name: '💀 绝了/笑死',  url: _T('1f480') },
      { name: '🫣 偷看',       url: _T('1fae3') },
      { name: '🫢 捂嘴',       url: _T('1fae2') },
      { name: '😮‍💨 无语叹气', url: _T('1f62e-200d-1f4a8') },
      { name: '🤯 脑壳炸了',   url: _T('1f92f') },
      { name: '🫡 收到!',      url: _T('1fae1') },
      { name: '🙃 呵呵',       url: _T('1f643') },
      { name: '😈 使坏',       url: _T('1f608') },
      { name: '🤪 疯狂',       url: _T('1f92a') },
      { name: '😵‍💫 晕了',    url: _T('1f635-200d-1f4ab') },
    ]
  },
  {
    id: 'cute-animal',
    name: '🐱 萌宠动物',
    items: [
      { name: '🐱 喵咪头',     url: _T('1f431') },
      { name: '😺 笑脸猫',     url: _T('1f63a') },
      { name: '😻 花痴猫',     url: _T('1f63b') },
      { name: '🙀 惊恐猫',     url: _T('1f640') },
      { name: '😿 哭泣猫',     url: _T('1f63f') },
      { name: '😹 笑哭猫',     url: _T('1f639') },
      { name: '🐶 狗狗头',     url: _T('1f436') },
      { name: '🐕 忠犬',       url: _T('1f415') },
      { name: '🐰 兔叽',       url: _T('1f430') },
      { name: '🐼 国宝熊猫',   url: _T('1f43c') },
      { name: '🦊 小狐狸',     url: _T('1f98a') },
      { name: '🐸 呱呱蛙',     url: _T('1f438') },
      { name: '🦄 独角兽',     url: _T('1f984') },
      { name: '🐧 企鹅仔',     url: _T('1f427') },
      { name: '🐥 小黄鸡',     url: _T('1f425') },
      { name: '🐻 小熊',       url: _T('1f43b') },
      { name: '🐨 考拉',       url: _T('1f428') },
      { name: '🦋 蝴蝶',       url: _T('1f98b') },
      { name: '🐢 乌龟',       url: _T('1f422') },
      { name: '🦔 刺猬',       url: _T('1f994') },
    ]
  },
  {
    id: 'heart-love',
    name: '💖 爱心合集',
    items: [
      { name: '❤️ 经典红心',   url: _T('2764') },
      { name: '💗 粉色心',     url: _T('1f497') },
      { name: '🧡 橙心',       url: _T('1f9e1') },
      { name: '💛 黄心',       url: _T('1f49b') },
      { name: '💚 绿心',       url: _T('1f49a') },
      { name: '💙 蓝心',       url: _T('1f499') },
      { name: '💜 紫心',       url: _T('1f49c') },
      { name: '🖤 黑心',       url: _T('1f5a4') },
      { name: '🤍 白心',       url: _T('1f90d') },
      { name: '🤎 棕心',       url: _T('1f90e') },
      { name: '💕 双心',       url: _T('1f495') },
      { name: '💖 闪亮心',     url: _T('1f496') },
      { name: '💗 心跳',       url: _T('1f497') },
      { name: '💘 一箭穿心',   url: _T('1f498') },
      { name: '💝 礼物心',     url: _T('1f49d') },
      { name: '💞 旋转双心',   url: _T('1f49e') },
      { name: '❣️ 心叹号',     url: _T('2763') },
      { name: '🫶 比心手势',   url: _T('1faf6') },
      { name: '😘 飞吻',       url: _T('1f618') },
      { name: '💋 红唇印',     url: _T('1f48b') },
    ]
  },
  {
    id: 'dessert',
    name: '🧁 甜品下午茶',
    items: [
      { name: '🧁 杯子蛋糕',   url: _T('1f9c1') },
      { name: '🍰 草莓蛋糕',   url: _T('1f370') },
      { name: '🎂 生日蛋糕',   url: _T('1f382') },
      { name: '🍩 甜甜圈',     url: _T('1f369') },
      { name: '🍪 曲奇饼',     url: _T('1f36a') },
      { name: '🍭 棒棒糖',     url: _T('1f36d') },
      { name: '🍬 糖果',       url: _T('1f36c') },
      { name: '🍫 巧克力',     url: _T('1f36b') },
      { name: '🧋 珍珠奶茶',   url: _T('1f9cb') },
      { name: '☕ 咖啡',       url: _T('2615') },
      { name: '🍦 冰淇淋',     url: _T('1f366') },
      { name: '🍨 冰淇淋杯',   url: _T('1f368') },
      { name: '🍡 团子',       url: _T('1f361') },
      { name: '🍓 草莓',       url: _T('1f353') },
      { name: '🍑 蜜桃',       url: _T('1f351') },
      { name: '🍒 樱桃',       url: _T('1f352') },
      { name: '🍇 葡萄',       url: _T('1f347') },
      { name: '🥑 牛油果',     url: _T('1f951') },
      { name: '🫧 泡泡',       url: _T('1fae7') },
      { name: '🧸 小熊软糖',   url: _T('1f9f8') },
    ]
  },
  {
    id: 'flower-nature',
    name: '🌸 花草自然',
    items: [
      { name: '🌸 樱花',       url: _T('1f338') },
      { name: '🌺 芙蓉花',     url: _T('1f33a') },
      { name: '🌻 向日葵',     url: _T('1f33b') },
      { name: '🌹 玫瑰',       url: _T('1f339') },
      { name: '🌷 郁金香',     url: _T('1f337') },
      { name: '💐 花束',       url: _T('1f490') },
      { name: '🪻 薰衣草',     url: _T('1fab7') },
      { name: '🌼 雏菊',       url: _T('1f33c') },
      { name: '🍀 四叶草',     url: _T('1f340') },
      { name: '🌈 彩虹',       url: _T('1f308') },
      { name: '⭐ 星星',       url: _T('2b50') },
      { name: '🌙 月亮',       url: _T('1f319') },
      { name: '☀️ 太阳',       url: _T('2600') },
      { name: '🌊 海浪',       url: _T('1f30a') },
      { name: '🦩 火烈鸟',     url: _T('1f9a9') },
      { name: '🐚 贝壳',       url: _T('1f41a') },
      { name: '🍄 蘑菇',       url: _T('1f344') },
      { name: '🌵 仙人掌',     url: _T('1f335') },
      { name: '🪴 盆栽',       url: _T('1fab4') },
      { name: '✨ 闪闪',       url: _T('2728') },
    ]
  },
  {
    id: 'fun-object',
    name: '🎮 趣味物品',
    items: [
      { name: '🎮 游戏手柄',   url: _T('1f3ae') },
      { name: '🕹️ 摇杆',       url: _T('1f579') },
      { name: '👾 像素外星人', url: _T('1f47e') },
      { name: '🤖 机器人',     url: _T('1f916') },
      { name: '👻 小幽灵',     url: _T('1f47b') },
      { name: '👽 外星人',     url: _T('1f47d') },
      { name: '🎪 马戏团',     url: _T('1f3aa') },
      { name: '🎨 调色盘',     url: _T('1f3a8') },
      { name: '🎸 吉他',       url: _T('1f3b8') },
      { name: '🎹 钢琴',       url: _T('1f3b9') },
      { name: '📷 相机',       url: _T('1f4f7') },
      { name: '🎧 耳机',       url: _T('1f3a7') },
      { name: '🧩 拼图',       url: _T('1f9e9') },
      { name: '🪩 迪斯科球',   url: _T('1faa9') },
      { name: '🏠 小房子',     url: _T('1f3e0') },
      { name: '🚀 火箭',       url: _T('1f680') },
      { name: '🎀 蝴蝶结',     url: _T('1f380') },
      { name: '👑 皇冠',       url: _T('1f451') },
      { name: '💎 钻石',       url: _T('1f48e') },
      { name: '🔮 水晶球',     url: _T('1f52e') },
    ]
  },
  {
    id: 'festival',
    name: '🎄 节日氛围',
    items: [
      { name: '🎄 圣诞树',     url: _T('1f384') },
      { name: '🎅 圣诞老人',   url: _T('1f385') },
      { name: '⛄ 雪人',       url: _T('26c4') },
      { name: '🎃 万圣南瓜',   url: _T('1f383') },
      { name: '🧧 红包',       url: _T('1f9e7') },
      { name: '🏮 灯笼',       url: _T('1f3ee') },
      { name: '🐲 龙',         url: _T('1f432') },
      { name: '🎆 烟花',       url: _T('1f386') },
      { name: '🎇 烟火',       url: _T('1f387') },
      { name: '🧨 鞭炮',       url: _T('1f9e8') },
      { name: '🎁 礼物盒',     url: _T('1f381') },
      { name: '🎊 庆祝彩带',   url: _T('1f38a') },
      { name: '🎋 七夕竹',     url: _T('1f38b') },
      { name: '🎑 赏月',       url: _T('1f391') },
      { name: '🥮 月饼',       url: _T('1f96e') },
      { name: '🪭 折扇',       url: _T('1faad') },
      { name: '🎐 风铃',       url: _T('1f390') },
      { name: '🪅 彩罐',       url: _T('1fa85') },
      { name: '🎪 帐篷',       url: _T('1f3aa') },
      { name: '🧲 磁铁',       url: _T('1f9f2') },
    ]
  },
  {
    id: 'gesture',
    name: '🤟 手势表达',
    items: [
      { name: '👍 点赞',       url: _T('1f44d') },
      { name: '✌️ 耶',         url: _T('270c') },
      { name: '🤟 爱你',       url: _T('1f91f') },
      { name: '🫶 比心',       url: _T('1faf6') },
      { name: '🤞 好运',       url: _T('1f91e') },
      { name: '👌 OK',         url: _T('1f44c') },
      { name: '💪 加油',       url: _T('1f4aa') },
      { name: '👋 拜拜',       url: _T('1f44b') },
      { name: '🙏 感谢',       url: _T('1f64f') },
      { name: '👏 鼓掌',       url: _T('1f44f') },
      { name: '🤙 Call',       url: _T('1f919') },
      { name: '🫰 嘎嘎',       url: _T('1faf0') },
      { name: '🤘 摇滚',       url: _T('1f918') },
      { name: '🫵 就是你',     url: _T('1faf5') },
      { name: '✊ 冲鸭',       url: _T('270a') },
      { name: '👊 碰拳',       url: _T('1f44a') },
      { name: '🤝 握手',       url: _T('1f91d') },
      { name: '🫲 摊手',       url: _T('1faf2') },
      { name: '☝️ 注意',       url: _T('261d') },
      { name: '🖖 Live long',  url: _T('1f596') },
    ]
  },
];
